Repository googleapis/code-suggester, pull requests merged in 2020-09, with the labels that each got.

#95 feat: return the PR created
  package.json
  src/github-handler/pull-request-handler.ts
  src/index.ts
  test/pr.ts
Labels: cla: yes, cla: yes

#98 feat(types): make "Changes" type public
  src/index.ts
Labels: cla: yes, cla: yes

#97 feat(logging): allow pino to be configured
  src/index.ts
  src/logger/index.ts
Labels: cla: yes, cla: yes

#101 feat: make forking functionality optional
  README.md
  src/index.ts
  src/types/index.ts
  test/main-make-pr.ts
Labels: cla: yes, cla: yes

#102 fix: listBranches fails if repo has many branches
  src/github-handler/branch-handler.ts
  test/branch.ts
  test/fixtures/get-ref-response.json
Labels: cla: yes, cla: yes

#107 build: let autorelease handle the release process
  .github/release-please.yml
Labels: cla: yes, cla: yes

#109 feat(cli,action): enable configuring --fork option
  README.md
  action.yaml
  entrypoint.sh
  src/bin/code-suggester.ts
  src/bin/workflow.ts
  test/cli.ts
Labels: automerge, cla: yes, cla: yes

#110 refactor(action): compile action from current checkout
  Dockerfile
  action.yaml
Labels: cla: yes, cla: yes

#114 feat(framework-core): main interface for create review on a pull request
  README.md
  src/default-options-handler.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/index.ts
  src/github-handler/comment-handler/index.ts
  src/github-handler/comment-handler/valid-patch-handler/index.ts
  src/github-handler/comment-handler/valid-patch-handler/upload-comments-handler.ts
  src/github-handler/index.ts
  src/index.ts
  src/types/index.ts
  test/helper-review-pull-request.ts
  test/inline-suggest.ts
  test/main-pr-option-defaults.ts
  test/main-review-pull-request.ts
Labels: cla: yes, cla: yes

#115 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full

#116 fix(framework-core): combine review comments
  src/github-handler/comment-handler/index.ts
  src/github-handler/comment-handler/invalid-hunk-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/message-handler.ts
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  test/helper-review-pull-request.ts
  test/inline-suggest.ts
  test/invalid-hunks.ts
  test/timeline-comment-invalid-hunks.ts
Labels: cla: yes, cla: yes

#117 feat(framework-core): return review number and variable renaming
  README.md
  src/github-handler/comment-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/hunk-to-patch-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/in-scope-hunks-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/index.ts
  src/github-handler/comment-handler/raw-patch-handler/raw-hunk-handler.ts
  src/index.ts
  src/types/index.ts
  test/helper-review-pull-request.ts
  test/hunk-to-patch.ts
  test/inline-suggest.ts
  test/main-review-pull-request.ts
  test/suggestion-hunk.ts
  test/suggestion-patch.ts
Labels: cla: yes, cla: yes
