Repository googleapis/code-suggester, pull requests merged in 2020-07, with the labels that each got.

#22 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, context: full

#20 feat: create a fork with Octokit given a repository name and its corresponding owner
  .gitattributes
  .gitignore
  package.json
  src/github-handler/fork-handler.ts
  src/github-handler/index.ts
  src/logger/index.ts
  src/types/index.ts
  synth.metadata
  test/fixtures/create-fork-response.json
  test/fork.ts
  test/util.ts
Labels: automerge

#12 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#26 chore(deps): remove unused protobuf, gax dependencies
  package.json
Labels: automerge

#28 build: update issues in gitattributes
  .gitattributes
  synth.metadata
Labels: context: none

#27 feat: create a branch from origin owner, repo, branch name, and an optional primary branch
  src/github-handler/branch-handler.ts
  src/github-handler/fork-handler.ts
  src/github-handler/index.ts
  src/types/index.ts
  test/branch.ts
  test/fixtures/create-branch-response.json
  test/fixtures/create-ref-response.json
  test/fork.ts
  test/util.ts
Labels: automerge

#32 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, context: full

#31 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge

#33 feat: basic pr opening
  src/github-handler/index.ts
  src/github-handler/pr-handler.ts
  src/types/index.ts
  test/fixtures/create-pr-response.json
  test/pr.ts
Labels: type: process

#38 fix: prevent cascading tests by having sinon reset all stubs
  test/branch.ts
  test/fork.ts
Labels: bug

#30 feat: commit and push changes onto a SHA to a target remote
  src/github-handler/commit-and-push-handler.ts
  src/github-handler/index.ts
  src/types/index.ts
  test/commit-and-push.ts
  test/fixtures/create-commit-response.json
  test/fixtures/create-fork-response.json
  test/fixtures/create-pr-response.json
  test/fixtures/create-tree-response.json
  test/fixtures/get-commit-response.json
Labels: automerge, type: process

#47 chore: initialize system tests
  system-test/main.test.ts
Labels: bug

#42 docs: interface of framework-core and the cli interface
  README.md
Labels: documentation

#41 build: update to latest docs config
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: context: partial

#39 build: add node.js 8 config for kokoro
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: context: none

#57 build: do not overwrite custom CODEOWNERS file
  synth.py
Labels: automerge
