Repository googleapis/code-suggester, pull requests merged in 2020-10, with the labels that each got.

#120 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full

#128 fix: handle single line comments and add newline
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  test/inline-suggest.ts
Labels: cla: yes, cla: yes

#125 fix: range parsing
  package.json
  src/github-handler/comment-handler/get-hunk-scope-handler/github-patch-text-handler.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/index.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/remote-patch-ranges-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/raw-hunk-handler.ts
  src/github-handler/diff-utils.ts
  test/diff-utils.ts
  test/fixtures/diffs/deletion.diff
  test/fixtures/diffs/many-to-many.diff
  test/fixtures/diffs/many-to-one.diff
  test/fixtures/diffs/one-line-to-many-newline.diff
  test/fixtures/diffs/one-line-to-many.diff
  test/fixtures/diffs/one-line-to-one.diff
  test/github-regex-patch.ts
  test/remote-github-patch-text.ts
  test/suggestion-hunk.ts
Labels: cla: yes, cla: yes

#131 fix(action): default upstream owner/repo to the current repo
  action.yaml
  entrypoint.sh
Labels: automerge, cla: yes, cla: yes

#121 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full

#130 feat(cli): add command for reviewing a pr
  src/bin/code-suggester.ts
  src/bin/handle-git-dir-change.ts
  src/bin/workflow.ts
  test/cli.ts
Labels: cla: yes, cla: yes

#132 refactor(review-pr): refactor to use hunks instead of Patch + new file content
  src/github-handler/comment-handler/get-hunk-scope-handler/index.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/remote-patch-ranges-handler.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/scope-handler.ts
  src/github-handler/comment-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/hunk-to-patch-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/in-scope-hunks-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/index.ts
  src/github-handler/diff-utils.ts
  src/types/index.ts
  test/diff-utils.ts
  test/fixtures/diffs/one-line-to-many-newline.diff
  test/helper-review-pull-request.ts
  test/hunk-to-patch.ts
  test/inline-suggest.ts
  test/pull-request-hunks.ts
  test/remote-github-patch-text.ts
  test/scope-handler.ts
  test/scope-suggestion-hunks.ts
  test/suggestion-patch.ts
Labels: cla: yes, cla: yes

#135 feat(action): action can now review pull requests
  README.md
  action.yaml
  entrypoint.sh
Labels: cla: yes, cla: yes

#137 feat(review): allow raw diff for reviewPullRequest
  src/bin/handle-git-dir-change.ts
  src/bin/workflow.ts
  src/github-handler/comment-handler/get-hunk-scope-handler/remote-patch-ranges-handler.ts
  src/github-handler/comment-handler/index.ts
  src/github-handler/diff-utils.ts
  src/index.ts
  test/diff-utils.ts
  test/helper-review-pull-request.ts
Labels: cla: yes, cla: yes

#140 fix: the review comment should go on the old file lines
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  test/inline-suggest.ts
Labels: cla: yes, cla: yes

#147 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full

#148 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full

#152 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: docs, automerge, cla: yes, cla: yes, context: full
