Repository googleapis/code-suggester, pull requests merged in 2020-08, with the labels that each got.

#54 chore: regenerate common templates
  .gitattributes
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, context: full

#64 chore: regenerate common templates
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
  synth.py
Labels: automerge, context: none

#66 fix(core-library): do not create pr when a pr already exists for a ref
  src/github-handler/fork-handler.ts
  src/github-handler/pull-request-handler.ts
  test/fixtures/list-pulls-response.json
  test/pr.ts
Labels: automerge

#69 feat(action): setup configuration for GitHub actions
  Dockerfile
  README.md
  action.yaml
  entrypoint.sh
Labels: automerge

#71 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, context: full

#77 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, context: full

#79 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, context: full

#78 fix(framework-core): retry mechanism for when forked git object isn't quite ready
  package.json
  src/github-handler/fork-handler.ts
  src/index.ts
  test/main-make-pr.ts
Labels: bug

#81 fix(cli,action): when process fails, make exit code 1
  entrypoint.sh
  src/bin/code-suggester.ts
Labels: automerge

#85 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, context: full

#94 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full
