Repository googleapis/code-suggester, pull requests merged in 2021-05, with the labels that each got.

#218 build: add generated-files config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#222 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#223 chore: update lockfile and re-format
  package-lock.json
  src/bin/handle-git-dir-change.ts
  src/github/review-pull-request.ts
  test/branch.ts
  test/inline-suggest.ts
  test/pr.ts
Labels: cla: yes

#224 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#226 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: cla: yes
