Repository googleapis/code-suggester, pull requests merged in 2021-03, with the labels that each got.

#175 fix: add labels to action.yaml
  action.yaml
Labels: cla: yes, cla: yes

#181 fix(deps): update to the latest version of octokit
  package-lock.json
  package.json
  src/github-handler/fork-handler.ts
  test/branch.ts
  test/commit-and-push.ts
  test/fork.ts
  test/inline-suggest.ts
  test/issues.ts
  test/pr.ts
  test/pull-request-hunks.ts
  test/remote-github-patch-text.ts
Labels: cla: yes

#182 chore: enable renovate lock file updates
  renovate.json
Labels: cla: yes

#193 chore: ignore updates to renovate config
  synth.py
Labels: automerge, cla: yes

#194 test: use assert.rejects and drop chai
  package-lock.json
  package.json
  src/bin/code-suggester.ts
  system-test/main.test.ts
  test/branch.ts
  test/cli.ts
  test/commit-and-push.ts
  test/diff-utils.ts
  test/fork.ts
  test/git-dir-handler.ts
  test/helper-review-pull-request.ts
  test/hunk-utils.ts
  test/inline-suggest.ts
  test/invalid-hunks.ts
  test/issues.ts
  test/main-make-pr.ts
  test/main-pr-option-defaults.ts
  test/main-review-pull-request.ts
  test/parse-text-files.ts
  test/pr.ts
  test/pull-request-hunks.ts
  test/remote-github-patch-text.ts
  test/scope-handler.ts
  test/suggestion-hunk.ts
Labels: cla: yes
