Repository googleapis/code-suggester, pull requests merged in 2021-04, with the labels that each got.

#198 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 build: on release, also create a major version tag
  .github/workflows/release.yaml
Labels: cla: yes

#207 feat: add optional draft flag to openPullRequest()
  src/github-handler/pull-request-handler.ts
  src/index.ts
  src/types.ts
  test/pr.ts
Labels: automerge, cla: yes

#206 feat!: cleanup custom logging
  package-lock.json
  package.json
  src/bin/handle-git-dir-change.ts
  src/index.ts
  src/logger.ts
  src/types.ts
  test/util.ts
Labels: automerge, cla: yes

#216 chore(deps): update to latest lock files
  package-lock.json
  test/branch.ts
Labels: automerge, cla: yes

#212 refactor!: move custom logger configuration into options
  src/bin/workflow.ts
  src/index.ts
  src/types.ts
  test/cli.ts
Labels: automerge, cla: yes

#208 refactor!: reorganize source code
  package-lock.json
  package.json
  src/github-handler/comment-handler/get-hunk-scope-handler/remote-patch-ranges-handler.ts
  src/github-handler/comment-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/index.ts
  src/github-handler/comment-handler/make-review-handler/message-handler.ts
  src/github-handler/comment-handler/make-review-handler/upload-comments-handler.ts
  src/github-handler/comment-handler/raw-patch-handler/raw-hunk-handler.ts
  src/github-handler/hunk-utils.ts
  src/github-handler/index.ts
  src/github/branch.ts
  src/github/commit-and-push.ts
  src/github/fork.ts
  src/github/labels.ts
  src/github/open-pull-request.ts
  src/github/review-pull-request.ts
  src/index.ts
  src/utils/diff-utils.ts
  src/utils/hunk-utils.ts
  test/branch.ts
  test/cli.ts
  test/commit-and-push.ts
  test/diff-utils.ts
  test/fork.ts
  test/helper-review-pull-request.ts
  test/hunk-utils.ts
  test/inline-suggest.ts
  test/invalid-hunks.ts
  test/issues.ts
  test/main-make-pr.ts
  test/main-review-pull-request.ts
  test/pr.ts
  test/pull-request-hunks.ts
  test/remote-github-patch-text.ts
  test/scope-handler.ts
  test/suggestion-hunk.ts
Labels: automerge, cla: yes
