Repository googleapis/code-suggester, pull requests merged in 2023-01, with the labels that each got.

#434 feat: throw new CommitError if an API error occurs during commit process
  package-lock.json
  src/errors.ts
  src/github/commit-and-push.ts
  src/github/create-commit.ts
  src/index.ts
  test/commit-and-push.ts
Labels: size: m

#443 chore: remove obsolete assignees from blunderbuss.yml
  .github/blunderbuss.yml
Labels: size: xs

#442 feat: introduce CommitSigner interface
  .eslintrc.json
  owlbot.py
  src/github/commit-and-push.ts
  src/github/create-commit.ts
  src/index.ts
  src/types.ts
  test/commit-and-push.ts
Labels: size: m

#448 chore: fix line endings
  action/dist/index.js
Labels: size: xl
